/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesIndexRouteImport } from './routes/features/index'
import { Route as FeaturesFeatureIdIndexRouteImport } from './routes/features/$featureId/index'
import { Route as FeaturesFeatureIdNewRouteImport } from './routes/features/$featureId/new'
import { Route as FeaturesFeatureIdEntityIdRouteImport } from './routes/features/$featureId/$entityId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesFeatureIdIndexRoute = FeaturesFeatureIdIndexRouteImport.update({
  id: '/features/$featureId/',
  path: '/features/$featureId/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesFeatureIdNewRoute = FeaturesFeatureIdNewRouteImport.update({
  id: '/features/$featureId/new',
  path: '/features/$featureId/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesFeatureIdEntityIdRoute =
  FeaturesFeatureIdEntityIdRouteImport.update({
    id: '/features/$featureId/$entityId',
    path: '/features/$featureId/$entityId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/features': typeof FeaturesIndexRoute
  '/features/$featureId/$entityId': typeof FeaturesFeatureIdEntityIdRoute
  '/features/$featureId/new': typeof FeaturesFeatureIdNewRoute
  '/features/$featureId': typeof FeaturesFeatureIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/features': typeof FeaturesIndexRoute
  '/features/$featureId/$entityId': typeof FeaturesFeatureIdEntityIdRoute
  '/features/$featureId/new': typeof FeaturesFeatureIdNewRoute
  '/features/$featureId': typeof FeaturesFeatureIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/features/': typeof FeaturesIndexRoute
  '/features/$featureId/$entityId': typeof FeaturesFeatureIdEntityIdRoute
  '/features/$featureId/new': typeof FeaturesFeatureIdNewRoute
  '/features/$featureId/': typeof FeaturesFeatureIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/features'
    | '/features/$featureId/$entityId'
    | '/features/$featureId/new'
    | '/features/$featureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/features'
    | '/features/$featureId/$entityId'
    | '/features/$featureId/new'
    | '/features/$featureId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/features/'
    | '/features/$featureId/$entityId'
    | '/features/$featureId/new'
    | '/features/$featureId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  FeaturesFeatureIdEntityIdRoute: typeof FeaturesFeatureIdEntityIdRoute
  FeaturesFeatureIdNewRoute: typeof FeaturesFeatureIdNewRoute
  FeaturesFeatureIdIndexRoute: typeof FeaturesFeatureIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$featureId/': {
      id: '/features/$featureId/'
      path: '/features/$featureId'
      fullPath: '/features/$featureId'
      preLoaderRoute: typeof FeaturesFeatureIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$featureId/new': {
      id: '/features/$featureId/new'
      path: '/features/$featureId/new'
      fullPath: '/features/$featureId/new'
      preLoaderRoute: typeof FeaturesFeatureIdNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$featureId/$entityId': {
      id: '/features/$featureId/$entityId'
      path: '/features/$featureId/$entityId'
      fullPath: '/features/$featureId/$entityId'
      preLoaderRoute: typeof FeaturesFeatureIdEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  FeaturesFeatureIdEntityIdRoute: FeaturesFeatureIdEntityIdRoute,
  FeaturesFeatureIdNewRoute: FeaturesFeatureIdNewRoute,
  FeaturesFeatureIdIndexRoute: FeaturesFeatureIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
